.\" $Id: estats_agent_accessors.3,v 1.1 2003/01/06 20:50:31 engelhar Exp $
.TH ESTATS_AGENT 3 "12 December 2002" "Estats Userland" "Estats"
.SH NAME
estats_get_agent_type, estats_get_agent_version \- get values from the
Estats agent opaque structure
.SH SYNOPSIS
.B #include <estats/estats.h>
.PP
.nf
.BI "int         estats_get_agent_type(estats_agent* " agent ");"
.BI "const char* estats_get_agent_version(estats_agent* " agent ");"
.fi
.SH DESCRIPTION
As the \fIestats_agent\fR structure is opaque, these functions exist to
fetch values from it without exposing its structure.
.SH RETURN VALUES
\fBestats_get_agent_type()\fR returns the type of the agent, which is
one of ESTATS_AGENT_TYPE_LOCAL or ESTATS_AGENT_TYPE_LOG.
.PP
\fBestats_get_agent_version()\fR returns the version of the agent as a
string, which is custom-defined by the particular type of agent.
.SH SEE ALSO
.BR libestats (3)
