.TH estats-config 1 "15 May 2011" "Estats Userland" "Estats"
.SH NAME
estats-config \- script to get information about the installed version of
\fIlibestats\fR
.SH SYNOPSIS
.B estats-config
[\fB\-\-prefix\fR]
[\fB\-\-exec\-prefix\fR]
[\fB\-\-version\fR]
[\fB\-\-libs\fR]
[\fB\-\-cflags\fR]
[\fB\-\-libdir\fR]
[\fB\-\-includedir\fR]
.SH DESCRIPTION
\fBestats-config\fR is a tool for developers that are writing software
which uses \fIlibestats\fP.  It provides such information as the
compiler and linker flags necessary to use \fIlibestats\fP.
.SH OPTIONS
\fBestats-config\fR accepts the following options:
.TP 4
.B \-\-version
Print the currently installed version of \fIlibestats\fP on the standard
output.
.TP 4
.B \-\-libs
Print the linker flags that are necessary to link a \fIlibestats\fP
program.
.TP 4
.B \-\-libdir
Print the path location of \fIlibestats\fP.
.TP 4
.B \-\-includedir
Print the path location of \fIlibestats\fP include files.
.TP 4
.B \-\-cflags
Print the compiler flags that are necessary to compile a
\fIlibestats\fP program.
.TP 4
.B \-\-prefix
Print the prefix that \fIlibestats\fP was installed into.
.TP 4
.B \-\-exec-prefix
Print the exec prefix that \fIlibestats\fP was installed into.
.SH SEE ALSO
.BR libestats (3)
