.TH deltavar 1 "15 May 2011" "Estats Userland" "Estats"
.SH NAME
deltavar \- monitor a single Estats variable, printing out the
difference in value per second.
.SH SYNOPSIS
.B deltavar
.I connection_id
.I var_name
.SH DESCRIPTION
\fBdeltavar\fR runs in an infinite loop, creating a snapshot of the
current value of the Estats variable \fIvar_name\fR from the connection
\fIconnection_id\fR once every second and printing out the difference
from the previous value.
.SH SEE ALSO
.BR readvar (1),
.BR readall (1),
.BR writevar (1),
.BR libestats (3)
