.TH readall 1 "15 May 2011" "Estats Userland" "Estats"
.SH NAME
readall \- read the current value of all TCP-Estats variables from all connections.
.SH SYNOPSIS
.B readall
.SH DESCRIPTION
\fBreadall\fR iterates over all connections, taking a snapshot of and printing out
all TCP-Estats variables from each one.
.SH SEE ALSO
.BR readvar (1),
.BR writevar (1),
.BR deltavar (1),
.BR libestats (3)

