.\" $Id: estats_connection_copy.3,v 1.1 2003/01/06 20:50:31 engelhar Exp $
.TH estats_connection_copy 3 "12 December 2002" "Estats Userland" "Estats"
.SH NAME
estats_connection_data_copy, estats_connection_free_local_copy,
estats_connection_new_local_copy \- copy Estats connection structures
.SH SYNOPSIS
.B #include <estats/estats.h>
.PP
.nf
.BI "int                estats_connection_data_copy(estats_connection* " dest ", estats_connection* " src ");"
.BI "estats_connection* estats_connection_new_local_copy(estats_connection* " src ");"
.BI "void               estats_connection_free_local_copy(estats_connection* " conn ");"
.fi
.SH DESCRIPTION
These functions allow users to copy the data from one Estats connection
structure to another.  \fBestats_connection_data_copy()\fR copies the
data directly over, while \fBestats_connection_new_local_copy()\fR
creates a new structure and copies that.
\fBestats_connection_free_local_copy()\fR frees a copy created by
\fBestats_connection_new_local_copy(0\fR.
.SH RETURN VALUES
\fBestats_connection_data_copy()\fR returns ESTATS_ERR_SUCCESS on
succes, and a failure code otherwise.
\fBestats_connection_new_local_copy()\fR returns a newly allocated
estats_connection structure on success, or \fBNULL\fI on failure.
.SH SEE ALSO
.BR libestats (3)
