.\" $Id: estats_var_find.3,v 1.1 2003/01/06 20:50:36 engelhar Exp $
.TH ESTATS_VAR 3 "26 February 2002" "Estats Userland" "Estats"
.SH NAME
estats_var_head, estats_var_next, estats_var_find \- find or iterate over
Estats variables
.SH SYNOPSIS
.B #include <estats/estats.h>
.PP
.nf
.BI "estats_var* estats_var_head(estats_group* " group ");"
.BI "estats_var* estats_var_next(estats_var* " var ");"
.BI "estats_var* estats_var_find(estats_group* " group ", const char* " name ");"
.fi
.SH DESCRIPTION
While a \fIestats_group\fR represents a set of similar variables to be
measured, the actual individual variables are represented by
\fIestats_var\fR.  These functions enable the searching and traversal of
the list of variables within a group.
.PP
\fBestats_var_head()\fR obtains the first variable in \fIgroup\fR.
\fBestats_var_next()\fR returns the next group in the agent after
\fIvar\fR.  \fBestats_var_find()\fR searches for a specific variable in
\fIgroup\fR that has the name \fIname\fR.
.SH RETURN VALUES
For \fBestats_var_head()\fR and \fBestats_var_next()\fR, the value
returned is the next variable in the sequence, or \fBNULL\fR if there is
an error or there are no variables left.
.PP
\fBestats_var_find()\fR returns the variable with the specified name, or
\fBNULL\fR if there is an error or the variable is not found.
.SH SEE ALSO
.BR estats_agent_find_var_and_group (3),
.BR libestats (3)
