.\" $Id: estats_var_accessors.3,v 1.1 2003/01/06 20:50:36 engelhar Exp $
.TH ESTATS_VAR 3 "12 December 2002" "Estats Userland" "Estats"
.SH NAME
estats_get_var_name, estats_get_var_size, estats_get_var_type \- get
values from the Estats variable opaque structure
.SH SYNOPSIS
.B #include <estats/estats.h>
.PP
.nf
.BI "const char* estats_get_var_name(estats_var* " var ");"
.BI "int         estats_get_var_type(estats_var* " var ");"
.BI "size_t      estats_get_var_size(estats_var* " var ");"
.fi
.SH DESCRIPTION
As the \fIestats_var\fR structure is opaque, these functions exist to
fetch values from it without exposing its structure.
.SH RETURN VALUES
\fBestats_get_var_name()\fR returns the text name of the variable.
.PP
\fBestats_get_var_type()\fR returns the type of the variable, which can
be one of the following: ESTATS_TYPE_INTEGER, ESTATS_TYPE_INTEGER32,
ESTATS_TYPE_INET_ADDRESS_IPV4, ESTATS_TYPE_COUNTER32,
ESTATS_TYPE_GAUGE32, ESTATS_TYPE_UNSIGNED32, ESTATS_TYPE_TIME_TICKS,
ESTATS_TYPE_COUNTER64, ESTATS_TYPE_INET_PORT_NUMBER,
ESTATS_TYPE_INET_ADDRESS, ESTATS_TYPE_INET_ADDRESS_IPV6.
.PP
\fBestats_get_var_size()\fR returns the size of the variable in bytes.
For example, the size of a ESTATS_TYPE_INET_ADDRESS_IPV6 variable is 16
(128 bits).
.SH SEE ALSO
.BR libestats (3)
